appname = "App name: {name}"
appname = appname.format(name = "Edit CLI")
print(appname)
openfile = str(input("What is the path of the file? "))
editoropen = str(input("Do you want to add to, overwrite or view the file? a/o/v "))
if editoropen == "v":
    print("Opening file...")
    print("---------------")
    filecontents = open(openfile,"r")
    print(filecontents.read())
elif editoropen == "a":
    print("Opening file for editing...")
    print("---------------------------")
    filecontents = open(openfile,"r")
    print(filecontents.read())
    print("---------------------------")
    linetoadd = str(input("Please enter a line to add to this file... "))
    filecontents = open(openfile,"a")
    filecontents.write("\n" + linetoadd)
    print("Added")
elif editoropen == "o":
    print("Opening file for editing...")
    print("---------------------------")
    filecontents = open(openfile,"r")
    print(filecontents.read())
    print("---------------------------")
    linetoadd = str(input("Please enter a line that will replace the content of this file... "))
    filecontents = open(openfile,"w")
    filecontents.write(linetoadd)
    print("Added")
